exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('scenarios').del()
    .then(function() {
      // Inserts seed entries
      return knex('scenarios').insert([{
          "scenario_num": 1,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "When a monster is discovered on the grounds of the Pathfinder Lodge at Heidmarch Manor in Magnimar, an investigation into its appearance leads the PCs deep under the City of Monuments and face to face with a burgeoning thieves guild.",
          "title": "Rise of the Goblin Guild",
        },
        {
          "scenario_num": 2,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "In the ruins of Xin-Bakrakhan's seat of power of the Runelord of Wrath, the Pathfinder Society stands on the verge of a great discovery, but first the brave agents exploring the ruins must survive ages-old dangers and contemporary threats to return with the knowledge and wealth they've unearthed.",
          "title": "In Wrath's Shadow",
        },
        {
          "scenario_num": 3,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "When the Golemworks in Magnimar starts reporting some 'problems' with their most recent batch of golems, the PCs are sent to investigate in the hope that the Pathfinder Society can get on good terms with the influential arcane organization.",
          "title": "The Golemworks Incident",
        },
        {
          "scenario_num": 4,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "The PCs are sent to map the Storval Stairs and ensure the stairs provide a safe route to the Storval Rise from Magnimar, but upon their arrival, they find the ancient site claimed and 'ruled' by the self-proclaimed King of the Storval Stairs. Only through guile, diplomacy, or cold steel will the Pathfinders ensure access to iconic Thassilonian location.",
          "title": "King of the Storval Stairs",
        },
        {
          "scenario_num": 5,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "The Pathfinders are sent to the Sanos Forest in central Varisia to assist an agent researching the fey who inhabit the remote wood. But like many seemingly routine tasks in a Pathfinder's adventuring career, the simple support mission quickly turns into an adventure the PCs aren't soon to forget, presuming they survive.",
          "title": "The Sanos Abduction",
        },
        {
          "scenario_num": 6,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "When an ally of the Society reports that her sister's business is being harassed by the Aspis Consortium in the Varisian city of Korvosa, a team of Pathfinder agents is dispatched to the Green Market to assist. What they find there is more than simple strong-arming and intimidation, however. What mysterious forces bring the popular market its unlikely success, and can the PCs stop the Aspis Consortium from gaining control of what could become a lucrative resource for the rival organization?",
          "title": "The Green Market",
        },
        {
          "scenario_num": 7,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "The Pathfinder Society has discovered a new Aspis Consortium base in the pirate city of Riddleport and sends a small team of agents to infiltrate the rival cell disguised as newly hired mercenaries from Magnimar. After proving their value to the Aspis Consortium by carrying out a number of tasks throughout the City of Cyphers, the Pathfinders can learn the location of one of the consortium's local allies and ensure that the support the Aspis Consortium is counting on from their friends won't come.",
          "title": "Severing Ties",
        },
        {
          "scenario_num": 8,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "An active cell of the cult of Lissala's ancient goddess of runes and obedience has been discovered in the Varisian town of Palin's Cove. Seeking a chance to learn about this long-lost faith not from millennia-old relics but from its current practice, a team of Pathfinders travels to the industrial seaside settlement to uncover the secret coven and infiltrate its services in the guise of prospective converts. Will the Pathfinders discover the knowledge they seek, or will the evil cult subvert them with its vile and seductive faith?",
          "title": "The Cultist's Kiss",
        },
        {
          "scenario_num": 9,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "The eldest daughter of the prominent Blakros family is set to wed an influential Hellknight, and the Pathfinder Society is invited to the festivities. Dressed for a wedding befitting royalty, a team of Pathfinders attend the ceremony on behalf of the Decemvirate, but will their presence ultimately strengthen the Society's relationship with the influential Blakroses, or will events at the wedding bring the already tenuous alliance to a breaking point?",
          "title": "The Blakros Matrimony",
        },
        {
          "scenario_num": 10,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "In Kaer Maga, the mysterious and dangerous cliffside City of Strangers in untamed Varisia, the Pathfinder Society will come face to face with a sect of the cult of Lissala who prey upon the city's most vulnerable denizens to increase their own power. To what end do they conduct the ancient Feast of Sigils ritual, and can the Pathfinders stop them before their evil plans come to fruition?",
          "title": "Feast of Sigils",
        },
        {
          "scenario_num": 11,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "A powerful ally of the Pathfinder Society has disappeared, and no one but the Pathfinders even remembers that she ever existed. Can the PCs discover the fate of their missing associate, or will all memory of her be erased completely from history?",
          "title": "The Disappeared",
        },
        {
          "scenario_num": 12,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "In the ruins of a fallen empire built on the power of sin lies the key to awakening a great evil from a time long gone. The Pathfinder Society isn't the only organization seeking this potent artifact, however, and the result of failure could mean disaster for the whole of Varisia and beyond.",
          "title": "The Refuge of Time",
        },
        {
          "scenario_num": 13,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "The Pathfinder Society sends a team of agents into a Hellknight citadel to free a wrongfully imprisoned ally. Among the law-bound knights, however, they may find that getting out of the prison isn't as easy as getting in.",
          "title": "Fortress of the Nail",
        },
        {
          "scenario_num": 14,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "Someone in the city of Magnimar is committing crimes and leaving evidence implicating the Pathfinder Society. It falls to the Pathfinders to get to the bottom of it, and what they find may signal the resurgence of an enemy thought long defeated.",
          "title": "My Enemy's Enemy",
        },
        {
          "scenario_num": 15,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "In the shadow of the cyclopean Cyphergate that spans Riddleport's harbor, the PCs find themselves embroiled in a dangerous plot of deception that one could only find in Varisia's infamous pirate port.",
          "title": "The Cyphermage Dilemma",
        },
        {
          "scenario_num": 16,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "For the past year, the Pathfinder Society has used the isolated demiplane contained in the Hao Jin Tapestry as a private adventuring realm and, since discovering a backdoor out of the demiplane, as a shortcut from the tapestry's location to a hidden corner of Varisia. But the tapestry wasn't designed for this purpose, and travel from Absalom to Varisia could be more efficient. Now a team of Pathfinders must discover how the infamous sorcerer known as the Ruby Phoenix created her private demiplane and enter the heart of the tapestry and alter the very nature of the magical realm.",
          "title": "The Fabric of Reality",
        },
        {
          "scenario_num": 17,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "On the edge of Varisia's Mierani Forest stand the ruins of an ancient guardtower that once served as the native elves' first line of defense against the threat of invasion from the bordering Thassilonian realm of Envy. Just as the elves fled Golarion to avoid the destruction of Earthfall, so too did they leave behind the Tower of the Ironwood Watch, which the Pathfinder Society now hopes to explore, a task that could prove more dangerous than anyone anticipates.",
          "title": "Tower of the Ironwood Watch",
        },
        {
          "scenario_num": 18,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "While many Pathfinders meet unfortunate fates in their ongoing explorations of the dangerous world of Golarion, some retire with decades' worth of treasure in their coffers, and their lives still intact. When one such Pathfinder approaches the Grand Lodge with the hidden location of her treasure vault, it falls upon a new generation of Pathfinders to retrieve from within a valuable keepsake. That they can keep anything other than the ex-Pathfinder's locket makes the assignment all the sweeter.",
          "title": "The Veteran's Vault",
        },
        {
          "scenario_num": 19,
          "season": 4,
          "low_level": 1,
          "high_level": 5,
          "description": "A veteran Pathfinder exploring the Fenwall Mountains of Varisia has begun sleepwalking, traveling through the dead of night in the same direction each time. The following mornings, however, he awakens injured and lost in the wilderness, never reaching the mysterious destination that drew him from his bed in the night. Something is calling Kalkamedes, something powerful, but unless he can make it safely to the source of his somnambulism, that power will remain a mystery. It falls to a team of Pathfinders to escort the sleepwalker to his destination and uncover the true nature of the strange phenomenon overtaking Kalkamedes's dreams.",
          "title": "The Night March of Kalkamedes",
        },
        {
          "scenario_num": 20,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "After countless divinations and the efforts of undercover agents throughout Varisia, the Pathfinder Society has discovered the location of the last component needed to awaken a sleeping runelord. In a mad dash to beat the cult of Lissala to this ancient Thassilonian ruin, the Pathfinders must do whatever it takes to ensure they and not the evil cultists acquire the power within. But the arcane components are not unguarded, and even after 10,000 years, the cost of ensuring the safety of the region could be higher than the veteran adventurers are prepared or willing to pay.",
          "title": "Words of the Ancients",
        },
        {
          "scenario_num": 21,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "On the eastern continent of Tian Xia, the Pathfinder Society remains a small player in the greater political landscape, but Amara Li, head of the Lantern Lodge in the teeming city of Goka, has plans to change that. In order to secure the Pathfinder Society's place as an influential organization on the far side of the world from the Grand Lodge in Absalom, she must orchestrate an alliance with the mysterious Way of the Kirin. But the longtime rival of the Pathfinder Society, the Aspis Consortium, has plans to form an alliance of its own, and if the consortium succeeds, the Pathfinder Society's hopes of cementing their place in the Dragon Empires could be dashed forever.",
          "title": "Way of the Kirin",
        },
        {
          "scenario_num": 22,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "The dwarven sky citadel of Janderhoff in eastern Varisia is one of the least visited settlements in the land, at least by non-dwarves. Nevertheless, the Pathfinder Society has been invited to assist in the excavation of a forgotten ruin within the large underground complex. What the fearless adventurers stand to find within could be the greatest discovery of the Age of Lost Omens, something sure to immortalize all involved in the pages of the Pathfinder Chronicles for ever more. But the ruins under Janderhoff aren't the end of the Pathfinders' journey; rather they illuminate a treacherous path ahead, from the familiar land of Varisia into much more dangerous territory.",
          "title": "Halls of Dwarven Lore",
        },
        {
          "scenario_num": 23,
          "season": 4,
          "low_level": 3,
          "high_level": 7,
          "description": "The Pathfinder Society's conflict with the Aspis Consortium in the frontier region of Varisia has come to a head, and the time to secure dominance of the ancient land is now. But despite mounting victories on the Society's part, the Aspis Consortium still has a few tricks up its sleeves, including several powerful agents from the Pathfinders' past who could prove too challenging an obstacle to surmount. Can the PCs end the ongoing struggle for control of the flow of ancient Thassilonian artifacts out of Varisia's ports, or will the Aspis Consortium succeed in keeping the Pathfinder Society ever in its shadow as it profits on the exploitation of the millennia?",
          "title": "Rivalry's End",
        },
        {
          "scenario_num": 24,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "The Pathfinder Society has discovered the hint of a monumental revelation, but in order to confirm their find, they must send a team of agents into the dangerous and unwelcoming orc-ruled Hold of Belkzen. While an expedition could easily be dispatched to the orc capital of Urgir, the Decemvirate urges caution to ensure success. Thus, a team of Pathfinders must seek out a guide in the Varisian orc city of Urglin. Can they navigate the treacherous city of denizens who wouldn't mind seeing them dead, or will the orcs' Second Home be the site of their final mission?",
          "title": "The Price of Friendhsip",
        },
        {
          "scenario_num": 25,
          "season": 4,
          "low_level": 5,
          "high_level": 9,
          "description": "Deep beneath the orc city of Urgir in the Hold of Belkzen lie the ruins of the ancient dwarven Sky Citadel of Koldukar, where awaits what could be the greatest discovery of the Age of Lost Omens: confirmation of the location of one of the lost Sky Citadels, built by the dwarves in their earliest days on the surface of Golarion. But reaching their destination won't be easy for the Pathfinders, and only the most skilled will survive Urgir and the terrors guarding the dwarves' long-abandoned secrets. Can they uncover the location of the lost Sky Citadel, or will the Pathfinders suffer the same fate as Koldukar; defeat at the hands of ruthless orcs and centuries of decay under the earth?",
          "title": "The Secrets Stones Keep",
        },
        {
          "scenario_num": 26,
          "season": 4,
          "low_level": 7,
          "high_level": 11,
          "description": "After a year of searching and risking life and limb, the agents of the Pathfinder Society have discovered the resting place of the Runelord of Sloth, who has been sequestered from the world at large for 10,000 years awaiting the proper time for his return. Thanks to the efforts of the sinister cult of Lissala, that time is now. In a desperate attempt to defeat this ancient evil once and for all, the Decemvirate sends its best agents, armed with relics found throughout ancient Thassilon, to foil the cult's last-ditch efforts to usher in a new era of tyranny and strife. Will the party succeed in preventing Krune's return to Golarion, or will the Pathfinder Society serve simply as a speed-bump in the runelord's path to domination over the entire region?",
          "title": "The Waking Rune",
        },
      ])
    });
};
